# Generated by Django 2.2.13 on 2020-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('vender', models.BooleanField(default=True, verbose_name='Se puede vender')),
                ('comprar', models.BooleanField(default=True, verbose_name='Se puede comprar')),
                ('tipo_producto', models.CharField(choices=[('Co', 'Consumible'), ('Se', 'Servicio'), ('Al', 'Almacenable')], default='Al', max_length=255, verbose_name='Tipo de Producto')),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo de Barras')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('coste', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coste')),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Peso')),
                ('volumen', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Volumen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/producto/', verbose_name='Imagen del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
