# Generated by Django 2.2.13 on 2020-06-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Atributo')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('vender', models.BooleanField(default=True, verbose_name='Se puede vender')),
                ('comprar', models.BooleanField(default=True, verbose_name='Se puede comprar')),
                ('tipo_producto', models.CharField(choices=[('Co', 'Consumible'), ('Se', 'Servicio'), ('Al', 'Almacenable')], default='Al', max_length=255, verbose_name='Tipo de Producto')),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo de Barras')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('coste', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Coste')),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Peso')),
                ('volumen', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Volumen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/producto/', verbose_name='Imagen del Producto')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad a Mano')),
                ('capacidad', models.PositiveIntegerField(default=0, verbose_name='Capacidad de Produccion')),
                ('caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad')),
                ('atributo', models.ManyToManyField(blank=True, related_name='AtributoProducto', to='Inventario.Atributo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Valores_Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('producto', models.ManyToManyField(to='Inventario.Producto')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ValorVariante', to='Inventario.Valores_Atributo')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='valores',
            field=models.ManyToManyField(blank=True, related_name='ValoresProducto', to='Inventario.Valores_Atributo'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='valor',
            field=models.ManyToManyField(related_name='ValorAtributo', to='Inventario.Valores_Atributo'),
        ),
    ]
