# Generated by Django 2.2.13 on 2020-06-16 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valores_Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad a Mano'),
        ),
        migrations.AddField(
            model_name='producto',
            name='capacidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad de Produccion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='coste',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Coste'),
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ValorVariante', to='Inventario.Valores_Atributo')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Atributo')),
                ('valor', models.ManyToManyField(related_name='ValorAtributo', to='Inventario.Valores_Atributo')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='atributo',
            field=models.ManyToManyField(blank=True, null=True, related_name='AtributoProducto', to='Inventario.Atributo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='valores',
            field=models.ManyToManyField(blank=True, null=True, related_name='ValoresProducto', to='Inventario.Valores_Atributo'),
        ),
    ]
