# Generated by Django 2.2.13 on 2020-06-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20200616_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='atributo',
            field=models.ManyToManyField(blank=True, related_name='AtributoProducto', to='Inventario.Atributo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valores',
            field=models.ManyToManyField(blank=True, related_name='ValoresProducto', to='Inventario.Valores_Atributo'),
        ),
    ]
