# Generated by Django 2.2.14 on 2020-07-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20200714_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variante',
            name='precio_venta',
        ),
    ]
