# Generated by Django 2.2.14 on 2020-07-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20200714_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='variante',
            field=models.ManyToManyField(blank=True, to='Inventario.Variante'),
        ),
    ]
