# Generated by Django 2.2.13 on 2020-06-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota/Descripcion')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicacion')),
                ('info_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Producto')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Variante')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota/Descripcion')),
                ('inicio', models.DateField(verbose_name='Fecha de Apertura')),
                ('final', models.DateField(verbose_name='Fecha de Culminacion')),
                ('info_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Producto')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Variante')),
            ],
            options={
                'verbose_name': 'Subasta',
                'verbose_name_plural': 'Subastas',
            },
        ),
    ]
