# Generated by Django 2.2.13 on 2020-06-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_publicacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Publicacion'),
        ),
    ]
