# Generated by Django 2.2.13 on 2020-06-19 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('S1', 'Sector Primario'), ('S2', 'Sector Secundario'), ('S3', 'Sector Terciario'), ('S4', 'Sector Cuaternario')], max_length=255, verbose_name='Sector')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completo')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio de la Compania')),
                ('rif', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registro de Informacion Fiscal')),
                ('movil', models.CharField(blank=True, max_length=8, null=True, verbose_name='Telefono Movil')),
                ('local', models.CharField(blank=True, max_length=8, null=True, verbose_name='Telefono Fijo')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('pagina', models.URLField(blank=True, null=True, verbose_name='Pagina Web')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.Sectores')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
