# Generated by Django 2.2.14 on 2020-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='local',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono Fijo'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='movil',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono Movil'),
        ),
    ]
