# Generated by Django 2.2.13 on 2020-06-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='sectores',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
    ]
