# Generated by Django 2.2.13 on 2020-06-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orden_compra',
            options={'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Ordenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='subastar',
            options={'verbose_name': 'Subastar', 'verbose_name_plural': 'Subastar'},
        ),
    ]
